[package]
name = "project"
version = "0.1.0"
edition = "2021"



[dependencies]
reqwest = "0.11"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
clap = "2.33"
